version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.large
    parallelism: 16
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update && nvidia-smi -L
      - checkout
      # Update our path
      - run: echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
      # Restore cached files to speed things up
      - restore_cache:
          keys:
            - cache-pip
      # Install the packages needed to build our documentation
      # This will depend on your particular package!
      - run: pip install --user sphinx memory_profiler sphinx_copybutton alabaster
      - run: pip install --user -I ./

      # Cache some files for a speedup in subsequent builds
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip
      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd doc
            make html
      # Tell Circle to store the documentation output in a folder that we can access later
      - store_artifacts:
          path: doc/_build/html/
          destination: html

# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - build_docs
